### ISSUE TITLE
missing  #include <BH1750.h>

### ISSUE THREAD

**Issue by Givy** [tjan90/Arduino-Raspberry-Mosquitto#1]
Hi Tanveer,
Downloaded your Arduino code, but I am gettiing the following issue.  Where can I download this file "BH1750.h"?

ResolveLibrary(BH1750.h)

  -> candidates: []

ArduinoMQTTRasp:4:10: fatal error: BH1750.h: No such file or directory

 #include <BH1750.h>

          ^~~~~~~~~~

compilation terminated.

Using library ArduinoMqttClient at version 0.1.6 in folder: S:\MyProject\AVR\Arduinosketchbook\libraries\ArduinoMqttClient 

Using library WiFiNINA at version 1.8.13 in folder: S:\MyProject\AVR\Arduinosketchbook\libraries\WiFiNINA 

Using library DHT_sensor_library at version 1.4.4 in folder: S:\MyProject\AVR\Arduinosketchbook\libraries\DHT_sensor_library 

exit status 1

BH1750.h: No such file or directory

Thanks.

**Comment by tjan90** [comment]
BH1750.h is the header file for ambient light sensor. You can install the library in arduino IDE. It should work after that.

**Comment by Givy** [comment]
Got it.  Thanks for your reply.
________________________________
